name: Generate Anki decks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-decks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate europe capital deck
        run: |
          npm install
          npm run gen-europe
          npm run gen-south-america
      - name: Commit files # transfer the new html files back into the repository
        run: |
          git config --local user.name "robotkevin"
          git add ./bin
          git commit -m "Generate Decks (automatic)"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
